{% set name = "split-normal" %}
{% set version = "0.1.0a2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: aa47846dcbdd003005230d0b0dc42106b85df968f1d3b5384e44ba7326a3daa2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - numpy >=1.17.3
    - scipy >=1.4.0
    - jax >=0.1.59
    - jaxlib >=0.1.40
    - python

test:
  imports:
    - split_normal

about:
  home: "https://github.com/probablyai/split-normal"
  license: MIT
  summary: "A tiny package implementing functions of the split normal distribution compatible with Numpy and JAX."

extra:
  recipe-maintainers:
    - probablyai
